kind: ConfigMap
apiVersion: v1
metadata:
  name: login-microservice-config
  namespace: grahasti
data:
  application.properties: |
    server.ssl.enabled=false
    url.user.microservice.getUsers=http://localhost:8082/api/getUsers
    url.user.microservice.addUser=http://localhost:8082/api/getUsers
