kind: ConfigMap
apiVersion: v1
metadata:
  name: login-microservice-config
  namespace: grahasti
data:
  application.properties: |
    server.ssl.enabled=false
    url.user.microservice.getUsers=http://users-microservice-svc.grahasti.svc.cluster.local:8080/api/getUsers
    url.user.microservice.addUser=http://users-microservice-svc.grahasti.svc.cluster.local:8080/api/getUsers
