apiVersion: v1
kind: Service
metadata:
  name: users-microservice-svc
  labels:
    discovery.3scale.net: 'true'
  annotations:
    discovery.3scale.net/port: '8988'
    discovery.3scale.net/scheme: http
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8082
  selector:
    app: users-microservice
