apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-microservice
  name: account-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-microservice
  template:
    metadata:
      labels:
        app: account-microservice
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - image: quay.io/lotp/account-microservice-is:1:/lotp/account-microservice-is:001
        imagePullPolicy: Always
        name: account-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
       
