apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-microservice
  name: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - image: quay.io/lotp/users-microservice-is:7ffbc
        imagePullPolicy: Always
        name: users-microservice
        ports:
        - containerPort: 8082
          protocol: TCP
