apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: users-microservice-pipeline
  namespace: lotp-pipelines
spec:
  params:
    - default: '1'
      description: Reference of the image buildah will produce.
      name: git-pushid
      type: string
    - default: maven-repo-cache
      description: maven home
      name: maven-settings
      type: string
    - default: quay.io
      description: Reference of the Image registry server.
      name: image-registry-server
      type: string
    - default: lotp
      description: Namespace where the deployment has to be performed
      name: namespace
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/Lord-of-the-Pods/users-microservice'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-build
      params:
        - name: GOALS
          value:
            - '-Dmaven.repo.local=$(params.maven-settings)'
            - verify
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.image-registry-server)/lotp/users-microservice-is
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: buildah-tag
      params:
        - name: IMAGE
          value: >-
            $(params.image-registry-server)/lotp/users-microservice-is:$(params.git-pushid)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
      runAfter:
        - maven-build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-deployment
      params:
        - name: deployment
          value: users-microservice
        - name: IMAGE
          value: >-
            $(params.image-registry-server)/lotp/users-microservice-is:$(params.git-pushid)
        - name: namespace
          value: $(params.namespace)
      runAfter:
        - buildah-tag
      taskRef:
        kind: Task
        name: update-deployment
    - name: gitops-task
      params:
        - name: configGitUrl
          value: 'https://github.com/Lord-of-the-Pods/lotp-cicd.git'
        - name: path
          value: Applications/Deployments
        - name: fileName
          value: users-microservice.yaml
        - name: imageName
          value: $(params.image-registry-server)/lotp/users-microservice-is
        - name: imageTag
          value: $(params.git-pushid)
        - name: userName
          value: vishnoi.abhishek
        - name: userEmail
          value: vishnoi.abhishek@hotmail.com
      runAfter:
        - update-deployment
      taskRef:
        kind: Task
        name: gitops-task
      workspaces:
        - name: gitops-workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: maven-settings
