apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-task
spec:
  params:
    - name: configGitUrl
      type: string
    - name: path
      type: string
    - name: fileName
      type: string
    - name: imageName
      type: string
    - name: imageTag
      type: string
    - name: userName
      type: string
    - name: userEmail
      type: string
  steps:
    - image: 'alpine/git:v2.26.2'
      name: update-yaml
      resources: {}
      script: >
        #!/usr/bin/env sh

        set -e

        git config --global user.email "$(inputs.params.userEmail)"

        git config --global user.name "$(inputs.params.userName)"

        rm -rf gitops

        git clone -b master $(inputs.params.configGitUrl) gitops

        cd gitops/$(inputs.params.path)

        echo "Get Last 5 characters of the "

        echo "Updating yaml"


        tag=$(inputs.params.imageTag)

        echo $tag

        last5chars=${tag: -5}

        echo $last5chars

        finalName=$(inputs.params.imageName):$last5chars

        sed -i "s#image: [a-zA-Z0-9|.\/|-]*:[a-zA-Z0-9|.]*#image: $finalName#" $(inputs.params.fileName)

        cat $(inputs.params.fileName)

        git add -u

        git commit -m "[tekton] updating deployment"

        git push
      workingDir: $(workspaces.gitops-workspace.path)
  workspaces:
    - name: gitops-workspace