apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  managedFields:
    - apiVersion: tekton.dev/v1beta1
  name: gradle-sonar
spec:
  steps:
    - args:
        - install
      image: 'gradle:5.6.2-jdk11'
      name: gradle-goals
      resources: {}
      script: |
        echo "Running the Gradle command for sonar"
        ./gradlew sonarqube \
          -Dsonar.projectKey=demo1 \
          -Dsonar.host.url=https://sonar-sonarqube.apps.cluster-2cdf.2cdf.example.opentlc.com \
          -Dsonar.login=sqp_d67da55d823040cf4f938e24f4eb70792807d346 

          
      workingDir: /workspace/output
  workspaces:
    - description: The workspace consisting of gradle project.
      name: output
