kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-run-sa-scc-rolebinding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: lotp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole