apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login-microservice
  name: login-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-microservice
  template:
    metadata:
      labels:
        app: login-microservice
    spec:
      containers:
      - image: quay.io/abvishno/oc-pipelines-login-microservice
        imagePullPolicy: Always
        name: login-microservice
        ports:
        - containerPort: 8080
          protocol: TCP