apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: users-microservice-trigger-template
spec:
  params:
  - name: git-repo-name
  - name: git-repo-url
  - name: git-revision
  - name: git-pushid
  - name: image-registry-server
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations: {}
      generateName: users-microservice-pipeline-$(tt.params.git-pushid)-
      labels:
        tekton.dev/pipeline: users-microservice-pipeline
      namespace: lotp-pipelines
    spec:
      serviceAccountName: pipeline
      params:
      - name: git-repo-name
        value: $(tt.params.git-repo-name)
      - name: git-repo-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: git-pushid
        value: $(tt.params.git-pushid)
      - name: image-registry-server
        value: quay.io
      pipelineRef:
        name: users-microservice-pipeline
      resources: []
      status: null
      workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: trigger2
