apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: microservice-trigger-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.html_url)
  - name: git-repo-name
    value: $(body.resource.repository.name)
  - name: git-revision
    value: $(body.resource.head_commit.id)
  - name: git-pushid
    value: $(body.resource.head_commit.id)
